spring:
  datasource:
    url: jdbc:postgresql://ep-divine-lake-a1vky427-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_7ijXVFQrbMn3

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true