spring:
  application:
    name: kickytime
  profiles:
    default: dev         # 기본은 dev (배포에서는 SPRING_PROFILES_ACTIVE=prod 로 덮어씀)
  web:
    resources:
      favicon:
        enabled: false

logging:
  level:
    org.springframework.security: INFO

server:
  port: 8080